### ISSUE TITLE
页面不可见时，onFrame方法不执行！

### ISSUE THREAD

**Issue by wangtager** [svga/SVGAPlayer-Web#103]
在页面可见时，onFrame方法会按frame自增的顺序依次执行
当切换浏览器的tab再切换回来时，onFrame方法会直接跳到当前帧执行。切换回来之前的onFrame没有执行。导致在指定帧的事件没有被处理。

比如: 
绑定了onFrame事件，在frame===10的时候需要执行指定的业务逻辑。
在frame===3的时候，切换了tab。过了一会儿再切换回来的时候frame===15。此时直接跳过了frame===10，导致业务逻辑没有被处理。

**Comment by pangjunpeng** [comment]
+1，线上被坑到了

**Comment by PonyCui** [comment]
逻辑的操作，不能和动画事件绑定。
