### ISSUE TITLE
TypeError: Cannot read property 'length' of null at r.push

### ISSUE THREAD

**Issue by wohaofang** [svga/SVGAPlayer-Web#106]
### 页面报错

- 使用**"svgaplayerweb": "^2.3.0"** 打包后    

android 手机 经常会报 TypeError: Cannot read property 'length' of null at r.push 错

报错位置 
_loadImages(s,void 0,i,function(){i.ver="2.0",e({movie:i,images:s})})}catch(t){throw r&&r(t),t}},
o.onloadend=function(){l.load_viaProto(o.response,e,r)},

**Comment by PangHuFatcat** [comment]
我和你遇到相同的问题

**Comment by PangHuFatcat** [comment]
解决方法 1: 把svga资源上传到oss得到链接, 然后parser.load(换成链接的形式或者base64)

**Comment by wohaofang** [comment]
> 解决方法1：把svga资源上传到oss得到链接，然后parser.load（换成链接的形式或者base64）

感谢  我试试去
