### ISSUE TITLE
能不能像svga-lite一样支持css控制宽高

### ISSUE THREAD

**Issue by zsytssk** [svga/SVGAPlayer-Web#111]
SVGAPlayer-Web 如果通过css width height 样式控制大小， 整个动画就会显示出现问题（动画会菜超出显示canvas大小，只显示一小部分）。svga-lite 在 edge 上报错，也无法使用...

**Comment by liveme** [comment]
试试设置 setContentMode

**Comment by choutuan** [comment]
> 试试设置 setContentMode

在哪里设置呢？

**Comment by liveme** [comment]
> > 试试设置 setContentMode
> 
> 在哪里设置呢？

setContentMode方法，文档有写。
