### ISSUE TITLE
小程序在组件中播放不了

### ISSUE THREAD

**Issue by he2014** [svga/SVGAPlayer-Web#113]
代码：
Component({
    properties: {},
    data: {},
    methods: {},
    ready() {
           const SVGA = require("./libs/svga.min")
            let parser = new SVGA.Parser()
            let canvas = wx.createSelectorQuery().in(this).select("#svgaPlayer")
            let player = new SVGA.Player(canvas)
            parser.load("https://cdn.jsdelivr.net/gh/svga/SVGA-Samples@master/angel.svga", function (videoItem) {
                player.setVideoItem(videoItem);
                player.startAnimation();
            })

    }
});

**Comment by shiyu123** [comment]
下载的是最新的svga.min.js吗，我项目中可以
