### ISSUE TITLE
小程序组件加载动画报错

### ISSUE THREAD

**Issue by hushipeng1995** [svga/SVGAPlayer-Web#117]
let parser = new SVGA.Parser()
      let player = new SVGA.Player(wx.createSelectorQuery().in(this).select("#myCanvas"))
      setTimeout(() => {
        parser.load("https://cdn.jsdelivr.net/gh/svga/SVGA-Samples@master/angel.svga", function (videoItem) {
          player.setVideoItem(videoItem);
          player.startAnimation();
        })
      }, 1000)

Cannot read property 'requestAnimationFrame' of undefined

**Comment by mencomao** [comment]
这个错误还存在

**Comment by lz-web** [comment]
大佬可以解决下小程序加载报 Cannot read property 'requestAnimationFrame' of undefined 的错误吗

**Comment by demaxiya1982** [comment]
这个错误需要微信解决 估计
这个是没有开放的html API

**Comment by abearxiong** [comment]
```
let parser = new SVGA.Parser()
  let player = new SVGA.Player(wx.createSelectorQuery().in(this).select("#myCanvas"))
  setTimeout(() => {
    parser.load("https://cdn.jsdelivr.net/gh/svga/SVGA-Samples@master/angel.svga", function (videoItem) {
    })
  }, 1000)

```
信不信，只要load就可以了

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Web/issues/97
