### ISSUE TITLE
onFrame方法参数ts类型检测报错

### ISSUE THREAD

**Issue by variinlkt** [svga/SVGAPlayer-Web#125]
文档写的使用方法是：
```
onFrame(callback: (frame: number): void): void; - 动画播放至某帧后回调

```
而在ts环境中使用该方法会报错：
![image](https://user-images.githubusercontent.com/26018217/92549003-ed5e2480-f28a-11ea-87da-4f73579c14e0.png)

版本：
```
"svgaplayerweb": "^2.3.1"
```

**Comment by CristinaSong** [comment]
同遇到这个问题，npm上最新版本没有修复

**Comment by lijialiang** [comment]
如果仅考虑兼容主流浏览器，可使用 [lite 版本](https://github.com/svga/SVGAPlayer-Web-Lite)，完美支持 ts 提示。
