### ISSUE TITLE
文档里写的自动加载是怎么使用？

### ISSUE THREAD

**Issue by FAOfao931013** [svga/SVGAPlayer-Web#128]
### 自动加载
为 canvas 元素添加以下属性
`<div src="rose_2.0.0.svga" loops="0" clearsAfterStop="true" style="styles..."></div>`
动画会在页面加载完成后播放

这个自动加载我在项目里用了没反应啊
我已经 `import SVGA from 'svgaplayerweb'`了

**Comment by liveme** [comment]
需要调用 SVGA.autoload
```js
new SVGA.autoload(document.querySelector('#demoCanvas'))
```
PR：https://github.com/svga/SVGAPlayer-Web/pull/131/commits/fbf7c9c45f8945a6fca27e940bb3763f32667953

但还是建议手动管理加载和执行
