### ISSUE TITLE
 官方案列在小程序加载svga动画,真机调试和扫码预览的方式都会报错

### ISSUE THREAD

**Issue by lz-web** [svga/SVGAPlayer-Web#132]
#问题: 官方案列在小程序可以正常显示svga动画,真机调试和扫码预览的方式都会报错
#重现方式:真机调试和扫码预览
![image](https://user-images.githubusercontent.com/55732016/98346311-bb7dfa00-2050-11eb-8dc4-d698df02f8b3.png)

![image](https://user-images.githubusercontent.com/55732016/98346246-a86b2a00-2050-11eb-95fc-1261e39259d3.png)
#希望可以尽快能给到解决方案,谢谢!

**Comment by abearxiong** [comment]
微信小程序不支持canvas真机调试

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Web/issues/97
请使用最新的 svga.min.js ，从仓库上下载，不要使用任何代码片段中的 svga.min.js。
