### ISSUE TITLE
可以提供一个播放错误的回调吗

### ISSUE THREAD

**Issue by BlueEyes-biao** [svga/SVGAPlayer-Web#139]
使用setImage的时候当传入的图片的地址有问题的时候，svga会报错，然后卡住，可以提供一个播放错误的回调吗

**Comment by lnts2015** [comment]
还有超时回调能否也提供一下？

**Comment by Naeemo** [comment]
> 使用setImage的时候当传入的图片的地址有问题的时候，svga会报错，然后卡住，可以提供一个播放错误的回调吗

可以自己提前加载catch一下临时解决

**Comment by Naeemo** [comment]
> 还有超时回调能否也提供一下？ 

超时回调是指什么超时？

**Comment by lijialiang** [comment]
如果仅考虑兼容主流浏览器，可使用 lite 版本，替换或动态元素全由外部逻辑可控制。
