### ISSUE TITLE
求助，脑袋要炸了，在cocosCreator中如何使用这个

### ISSUE THREAD

**Issue by df257** [svga/SVGAPlayer-Web#140]
我这边在cocos中用了会出现这个报错
![image](https://user-images.githubusercontent.com/7835444/109623463-21e6d500-7b78-11eb-9613-ba00c26e7298.png)

**Comment by PonyCui** [comment]
应该不支持在 cocos 中使用吧，毕竟没有为游戏引擎适配过。
不过，可以考虑写一个 cocos 的 SVGAPlayer。
