### ISSUE TITLE
Pako is unneeded？

### ISSUE THREAD

**Issue by L-Chris** [svga/SVGAPlayer-Web#141]
现代浏览器和web服务器都标配压缩、解压功能，Pako是否用处不大呢？
当svga文件内包含大量图片等数据时，压缩结果反而更大？

建议去除pako?

**Comment by PonyCui** [comment]
除图片以外，还有一堆二进制的动画描述数据，是需要 zlib 压缩的。
当初设计 2.0 格式的时候没有考虑到服务器自带压缩的事情，所以就默认压缩了。
