### ISSUE TITLE
onfinish回调方法在页面没有激活的状态下，没有回调成功

### ISSUE THREAD

**Issue by superOnes** [svga/SVGAPlayer-Web#147]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by Naeemo** [comment]
确实有这个问题，用定时器临时解决了。可以试一下 `noExecutionDelay`

**Comment by superOnes** [comment]
noExecutionDelay不是lite版的吗，web版的也有这个方法吗

**Comment by Naeemo** [comment]
啊！对不起，我搞错了……

**Comment by superOnes** [comment]
所以这个有办法解决吗

**Comment by lijialiang** [comment]
Web 版本暂不支持，需要考虑 WebWorker 兼容性问题，暂无可靠方式进行回调。

如果仅考虑兼容主流浏览器，建议使用 lite 版本。
