### ISSUE TITLE
Typo in renderer's path command validtion?

### ISSUE THREAD

**Issue by Naeemo** [svga/SVGAPlayer-Web#148]
[`src/Canvas/renderer.js`](https://github.com/svga/SVGAPlayer-Web/blob/master/src/Canvas/renderer.js) uses `validMethods`  to filter out unknown [path commands](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#path_commands).
Notice both `R` and `r` are in there, which probably should be `A` and `a` for elliptical arc curve.

---

https://github.com/svga/SVGAPlayer-Web/blob/de4af292b04565a9817725a7b4361ea16e2f3dbe/src/Canvas/renderer.js#L5

https://github.com/svga/SVGAPlayer-Web/blob/de4af292b04565a9817725a7b4361ea16e2f3dbe/src/Canvas/renderer.js#L308-L311

https://github.com/svga/SVGAPlayer-Web/blob/de4af292b04565a9817725a7b4361ea16e2f3dbe/src/Canvas/renderer.js#L426-L429

**Comment by Naeemo** [comment]
This is harmless however, both the two commands are not rendered by the renderer.

**Comment by PonyCui** [comment]
emm, yes.
