### ISSUE TITLE
初始化多个实例后内存增加得不到释放

### ISSUE THREAD

**Issue by zwjtheone** [svga/SVGAPlayer-Web#155]
初始化多个实例后内存增加得不到释放？
尝试调用clear和clearDynamicObjects方法后，memory依旧不减。请问是否有方法销毁加载的资源或者实例？或者是该插件有内存泄漏的问题

**Comment by lijialiang** [comment]
如果只考虑兼容主流浏览器，可使用 [lite 版本](https://github.com/svga/SVGAPlayer-Web-Lite)，有单独的 destroy 方法。
