### ISSUE TITLE
V2.3.2 SSR: window is not defined

### ISSUE THREAD

**Issue by billwing** [svga/SVGAPlayer-Web#159]
2.3.1:
![image](https://user-images.githubusercontent.com/3411815/123356522-733d2900-d59a-11eb-926c-737132cbcbe9.png)
2.3.2:
![image](https://user-images.githubusercontent.com/3411815/123356546-7d5f2780-d59a-11eb-861f-0957c9ef7e19.png)

2.3.2在服务端渲染项目报错：window is not defined (svga.min.js)

**Comment by abaddonpoet** [comment]
同问～能否有支持react服务端渲染的版本～

**Comment by lijialiang** [comment]
[目前版本 alpha](https://github.com/svga/SVGAPlayer-Web-Lite/tree/2.0) 中，待通过测试用例后发布正式版本

```tsx
import React, { useRef, useEffect } from 'react'
import { Parser, Player } from 'svga'

const Home: React.FC = () => {
  const canvas = useRef(null)

  useEffect(() => {
    async function playSvga (): Promise<void> {
      const canvasElement = canvas.current as unknown as HTMLCanvasElement
      const parser = new Parser()
      const svga = await parser.load('https://ovo-oss.duowan.com/upload/1625559566457.svga')
      const player = new Player(canvasElement)
      await player.mount(svga)
      player.start()
    }
    playSvga().catch(error => console.error(error))
  })

  return (
    <canvas ref={canvas} />
  )
}

export default Home
```

**Comment by lijialiang** [comment]
可使用 lite 版本 [v2.0.0](https://www.npmjs.com/package/svga)。

**Comment by Attax** [comment]
> 可使用 lite 版本 [v2.0.0](https://www.npmjs.com/package/svga)。

使用gatsby 有同样的问题，尝试修改gatsby-node.js配置 后出现documet is not defined问题。使用lite版本虽然没有window is not defined 但是也存在document is not defined 问题
