### ISSUE TITLE
非闭合的路径导出svga后被闭合

### ISSUE THREAD

**Issue by EggKim** [svga/SVGAPlayer-Web#160]
![image](https://user-images.githubusercontent.com/39717399/124536228-30a50780-de4a-11eb-9b4d-8daa590fea65.png)

**Comment by EggKim** [comment]
[礼物招呼.aep.zip](https://github.com/svga/SVGAPlayer-Web/files/6767179/aep.zip)

**Comment by PonyCui** [comment]
安装新版本 ae 扩展解决问题
