### ISSUE TITLE
在vue3.0里使用svga，会提示doesn't work properly without JavaScript enabled. Please enable it to continue.？

### ISSUE THREAD

**Issue by df257** [svga/SVGAPlayer-Web#163]
const svga = await parser.load("@/assets/example.svga");用这个去加载的时候，会报
![image](https://user-images.githubusercontent.com/7835444/131239219-a14db81b-5f95-4833-8de9-6de90a35c8aa.png)
所以我改成了
const svga = require("@/assets/example.svga");
但这样，好像需要加个loader，不知道该怎么加
![image](https://user-images.githubusercontent.com/7835444/131239245-45959105-92a6-42c2-94cd-ce70261b2d03.png)

**Comment by df257** [comment]
好吧，放public里就好了。。。

**Comment by lijialiang** [comment]
@df257 这里有 [Webpack 配置](https://github.com/svga/SVGAPlayer-Web-Lite#webpack-svga) 的例子，可以参考下。
