### ISSUE TITLE
svg没有播放。文件太大？

### ISSUE THREAD

**Issue by weixiaoting** [svga/SVGAPlayer-Web#96]
在直播间送特效礼物的情况下， 需要显示弹窗-播放礼物特效，播放结束之后弹窗隐藏。

parser.load(svga_url, function (
             videoItem) {
             player.setVideoItem(videoItem);
            player.loops = 1;
             player.startAnimation();
        }, function (err) {
            alert(err.message)
        })
player.onFinished(function () {
             console.log('svg播放结束')
         })

正常情况下，Svg正常播放并且播放完之后输出‘svg播放结束’。
但是svg也没有播放，也没有任何输出没有任何alert。
怎么设置在svg加载完成后再播放动效？？

**Comment by muriel01** [comment]
你好，问题解决没？

**Comment by iwowen** [comment]
我也遇到了，有没有解决呢？

**Comment by muriel01** [comment]
跟大小没关系，你使用的线上地址不？有可能是地址问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-Web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 中午11:15
收件人:&nbsp;"svga/SVGAPlayer-Web"<SVGAPlayer-Web@noreply.github.com&gt;;
抄送:&nbsp;"吴先先"<2424759141@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-Web] svg没有播放。文件太大？ (#96)





 
我也遇到了，有没有解决呢？

**Comment by liveme** [comment]
提供一下在线 DEMO

**Comment by muriel01** [comment]
之后换了文件地址可以正常播放，应该跟文件域名有关


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-Web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 下午4:51
收件人:&nbsp;"svga/SVGAPlayer-Web"<SVGAPlayer-Web@noreply.github.com&gt;;
抄送:&nbsp;"吴先先"<2424759141@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-Web] svg没有播放。文件太大？ (#96)





 
提供一下在线 DEMO
