### ISSUE TITLE
小程序报错找不到属性requestAnimationFrame

### ISSUE THREAD

**Issue by lvyunf3** [svga/SVGAPlayer-Web#97]
有时候svga动画加载不出来，就报这种错误；前后打印的是
canvas容器和元素节点![image](https://user-images.githubusercontent.com/51684353/78101707-f82ea680-741a-11ea-83f7-d5fc27547f39.png)

**Comment by shiyu123** [comment]
用最新的svga.min.js

**Comment by GerryIsWarrior** [comment]
问题解决了吗？我真机调试的时候，现在也是这个样子

**Comment by shiyu123** [comment]
> 问题解决了吗？我真机调试的时候，现在也是这个样子

我引入最新的svga.min.js就不会这样了

**Comment by mencomao** [comment]
想问一下，https://developers.weixin.qq.com/s/57sWDkmq7Eeu 这个代码片段的svga.min是最新的么？

**Comment by mencomao** [comment]
@shiyu123
